apiVersion: apps/v1
kind: Deployment
metadata:
  name: delegate-proxy
  annotations:
    {{- toYaml .Values.deployment.annotations | nindent 4 }}
  labels:
    {{- include "harness.deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.delegate_proxy.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: delegate-proxy
  template:
    metadata:
      annotations:
        {{- toYaml .Values.replica.annotations | nindent 8 }}
      labels:
        app: delegate-proxy
        {{- include "harness.replica.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "harness.serviceAccountName" . }}
      securityContext:
        runAsUser: 65534
      containers:
        - image: harness/delegate-proxy-signed:{{ .Values.versions.delegate_proxy }}
          imagePullPolicy: IfNotPresent
          name: delegate-proxy
          resources:
            limits:
              memory: {{ .Values.delegate_proxy.resources.limits.memory }}
              cpu: {{ .Values.delegate_proxy.resources.limits.cpu }}
            requests:
              memory: {{ .Values.delegate_proxy.resources.requests.memory }}
              cpu: {{ .Values.delegate_proxy.resources.requests.cpu }}

---

apiVersion: v1
kind: Service
metadata:
  name: delegate-proxy
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "harness.service.labels" . | nindent 4 }}
spec:
  selector:
    app: delegate-proxy
  ports:
    - name: http
      port: 8080
