apiVersion: v1
kind: ConfigMap
metadata:
  name: ng-manager
  annotations:
    {{- toYaml .Values.configMap.annotations | nindent 4 }}
  labels:
    {{- include "harness.configMap.labels" . | nindent 4 }}
data:
  AUDIT_ENABLED: 'false'
  CACHE_BACKEND: REDIS
  COMMON_POOL_CORE_SIZE: '{{ .Values.ng_manager.config.common_pool_core_size | default "1" }}'
  COMMON_POOL_MAX_SIZE: '{{ .Values.ng_manager.config.common_pool_max_size | default "5" }}'
  CURRENT_GEN_UI_URL: http://proxy/#/
  DEPLOY_MODE: KUBERNETES_ONPREM
  DEPLOY_VERSION: COMMUNITY
  DISABLE_RESOURCE_VALIDATION: 'true'
  DISTRIBUTED_LOCK_IMPLEMENTATION: REDIS
  ENABLE_DEFAULT_RESOURCE_GROUP_CREATION: 'true'
  ENABLE_SERIALGC: 'true'
  EVENTS_FRAMEWORK_NETTY_THREADS: '{{ .Values.ng_manager.config.events_framework_netty_threads | default "1" }}'
  EVENTS_FRAMEWORK_REDIS_URL: redis://redis:6379
  GIT_FULLSYNC_ENTITY_ITERATOR_THREAD_POOL_SIZE: '{{ .Values.ng_manager.config.git_fullsync_entity_iterator_thread_pool_size | default "2" }}'
  GRPC_SERVER_PORT: '9979'
  HARNESS_ENABLE_NG_AUTH_UI_PLACEHOLDER: 'true'
  JAVA_ADVANCED_FLAGS: -XX:-TieredCompilation
  LICENSE_DEPLOY_VARIANT: COMMUNITY
  LOCK_CONFIG_REDIS_URL: redis://redis:6379
  LOGGING_LEVEL: WARN
  LOG_STREAMING_SERVICE_BASEURL: http://proxy/log-service/
  LOG_STREAMING_SERVICE_TOKEN: c76e567a-b341-404d-a8dd-d9738714eb82
  MANAGER_AUTHORITY: default-authority.harness.io
  MANAGER_CLIENT_BASEURL: http://proxy/api/
  MANAGER_TARGET: manager:9879
  MANAGER_UI_URL: http://proxy
  MEMORY: '{{ .Values.ng_manager.config.memory }}m'
  MOCK_ACCESS_CONTROL_SERVICE: 'true'
  NG_MANAGER_API_URL: http://proxy/ng/api/
  NG_MANAGER_AUTHORITY: default-authority.harness.io
  NG_MANAGER_CLIENT_BASEURL: http://proxy/ng/api/
  NG_MANAGER_TARGET: localhost:13002
  NG_MANAGER_UI_URL: http://proxy/ng/#/
  NG_VAULT_ITERATOR_THREAD_POOL_SIZE: '{{ .Values.ng_manager.config.ng_vault_iterator_thread_pool_size | default "2" }}'
  PMS_AUTHORITY: default-authority.harness.io
  PMS_GITSYNC_AUTHORITY: default-authority.harness.io
  PMS_GITSYNC_TARGET: pipeline-service:14002
  PMS_SDK_EXECUTION_POOL_CORE_SIZE: '{{ .Values.ng_manager.config.pms_sdk_execution_pool_core_size | default "1" }}'
  PMS_SDK_EXECUTION_POOL_MAX_SIZE: '{{ .Values.ng_manager.config.pms_sdk_execution_pool_max_size | default "2" }}'
  PMS_SDK_ORCHESTRATION_EVENT_POOL_CORE_SIZE: '{{ .Values.ng_manager.config.pms_sdk_orchestration_event_pool_core_size | default "1" }}'
  PMS_SDK_ORCHESTRATION_EVENT_POOL_MAX_SIZE: '{{ .Values.ng_manager.config.pms_sdk_orchestration_event_pool_max_size | default "2" }}'
  PMS_TARGET: pipeline-service:12011
  REDIS_NETTY_THREADS: '{{ .Values.ng_manager.config.redis_netty_threads | default "1" }}'
  RESOURCE_GROUP_BASE_URL: http://proxy/resourcegroup/api/
  SCM_SERVICE_URI: scm:8091
  SEGMENT_ENABLED: 'true'
  SEGMENT_URL: https://stats.drone.ci/api/v1/
  SERVER_MAX_THREADS: '{{ .Values.ng_manager.config.server_max_threads | default "16" }}'
  SHOULD_CONFIGURE_WITH_PMS: 'true'
  USE_REDIS_FOR_SDK_RESPONSE_EVENTS: 'true'
  WEBHOOK_EVENT_PROCESSING_SERVICE_THREAD_SIZE: '{{ .Values.ng_manager.config.webhook_event_processing_service_thread_size | default "2" }}'

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ng-manager
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 }}
  labels:
    {{- include "harness.secret.labels" . | nindent 4 }}
stringData:
  MONGO_URI: 'mongodb://admin:dOkcGof8zL@mongodb-replicaset-chart.{{ .Release.Namespace }}.svc/ng-harness?authSource=admin'
  PMS_MONGO_URI: 'mongodb://admin:dOkcGof8zL@mongodb-replicaset-chart.{{ .Release.Namespace }}.svc/pms-harness?authSource=admin'
  NOTIFICATION_MONGO_URI: 'mongodb://admin:dOkcGof8zL@mongodb-replicaset-chart.{{ .Release.Namespace }}.svc/notifications?authSource=admin'

---

apiVersion: v1
kind: Service
metadata:
  name: ng-manager
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "harness.service.labels" . | nindent 4 }}
spec:
  ports:
  - name: http-ng-manager
    port: 7090
  - name: ng-manager-grpc
    port: 9979
  - name: gitsync-grpc
    port: 13002
  selector:
    app: ng-manager

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-manager
  annotations:
    {{- toYaml .Values.deployment.annotations | nindent 4 }}
  labels:
    app: ng-manager
    {{- include "harness.deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ng_manager.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: ng-manager
  template:
    metadata:
      annotations:
        {{- toYaml .Values.replica.annotations | nindent 8 }}
      labels:
        app: ng-manager
        {{- include "harness.replica.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "harness.serviceAccountName" . }}
      initContainers:
        - name: check-for-pms
          image: harness/nginx:{{ .Values.versions.nginx }}
          command: ['sh', '-c', "until curl -s http://pipeline-service:12001/api/health; do echo waiting for pipeline-service; sleep 2; done"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
      containers:
      - name: ng-manager
        image: harness/ng-manager-signed:{{ .Values.versions.manager }}
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 65534
          runAsNonRoot: true
        ports:
        - name: http-ng-manager
          containerPort: 7090
          protocol: "TCP"
        - name: ng-manager-grpc
          containerPort: 9979
          protocol: "TCP"
        - name: gitsync-grpc
          containerPort: 13002
          protocol: "TCP"
        envFrom:
        - configMapRef:
            name: ng-manager
        - secretRef:
            name: ng-manager
        readinessProbe:
          httpGet:
            path: /health
            port: 7090
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /health
            port: 7090
          initialDelaySeconds: 90
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 10
        resources:
          limits:
            memory: {{ .Values.ng_manager.resources.limits.memory }}
            cpu: {{ .Values.ng_manager.resources.limits.cpu }}
          requests:
            memory: {{ .Values.ng_manager.resources.requests.memory }}
            cpu: {{ .Values.ng_manager.resources.requests.cpu }}
