apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  annotations:
    {{- toYaml .Values.configMap.annotations | nindent 4 }}
  labels:
    app: redis
    {{- include "harness.configMap.labels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    app: redis
    {{- include "harness.service.labels" . | nindent 4 }}
spec:
  selector:
    app: redis
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  annotations:
    {{- toYaml .Values.deployment.annotations | nindent 4 }}
  labels:
    app: redis
    {{- include "harness.deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      annotations:
        {{- toYaml .Values.replica.annotations | nindent 8 }}
      labels:
        app: redis
        {{- include "harness.replica.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "harness.serviceAccountName" . }}
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: redis
        image: harness/redis:{{ .Values.versions.redis }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: data
        resources:
          limits:
            memory: {{ .Values.redis.resources.limits.memory }}
            cpu: {{ .Values.redis.resources.limits.cpu }}
          requests:
            memory: {{ .Values.redis.resources.requests.memory }}
            cpu: {{ .Values.redis.resources.requests.cpu }}
      volumes:
      - name: data
        emptyDir: {}
